name: Build Dolphin Libretro (Android ARMv7, no-JIT)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build pkg-config build-essential git

      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27

      - name: Confirm NDK location
        run: |
          echo "NDK root = ${{ steps.setup-ndk.outputs.ndk-root }}"
          ls -la ${{ steps.setup-ndk.outputs.ndk-root }}/build/cmake/

      - name: Configure (CMake) for ARMv7 no-JIT
        run: |
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=${{ steps.setup-ndk.outputs.ndk-root }}/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=armeabi-v7a \
            -DANDROID_PLATFORM=android-21 \
            -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_GENERIC=ON \
            -DDISABLE_JIT=ON \
            -DDOLPHIN_GENERIC_BUILD=ON \
            -G Ninja

      - name: Build (parallel)
        run: |
          cd build
          ninja -j$(nproc)

      - name: Show build outputs
        run: |
          echo "=== build outputs ==="
          find build -type f -name "*.so" -print

      - name: Upload built core(s)
        uses: actions/upload-artifact@v4
        with:
          name: dolphin-libretro-armv7-nojit
          path: |
            build/*.so
            build/**/dolphin_libretro*.so
